# START_VERSION_BLOCK
VERSION_MAJOR = 0
VERSION_MINOR = 0
VERSION_BUILD = 2
VERSION_ALPHA = 1
# END_VERSION_BLOCK

__version__ = '.'.join(map(str, [VERSION_MAJOR, VERSION_MINOR, VERSION_BUILD]))
if VERSION_ALPHA:
    __version__ += f'a{VERSION_ALPHA}'
